### ISSUE TITLE
The Text Looks Dull in Overlay for Anniversary post

### ISSUE THREAD

**Issue by vighneshmufc** [CLIxIndia-Dev/clixoer#100]
**Describe the bug**
The Text Looks Dull in Overlay since its a normal H3.. Use Some style and center align (Highlighted on SS)
![Screenshot (356)](https://user-images.githubusercontent.com/14256897/102209407-b7b68080-3ef6-11eb-9976-163f870de51f.png)

**Comment by yogeshu** [comment]
check this if need more
![Screenshot from 2020-12-16 11-51-11](https://user-images.githubusercontent.com/32289745/102312825-6ad5b700-3f95-11eb-8ff7-3d367f9c8d17.png)

**Comment by vighneshmufc** [comment]
Increase the Size 
Remove the -> at the button below survey button

**Comment by yogeshu** [comment]
![Screenshot from 2020-12-16 17-43-50](https://user-images.githubusercontent.com/32289745/102347384-5a8a0000-3fc6-11eb-885a-033ba4ff3b62.png)

**Comment by vighneshmufc** [comment]
Need to test on staging

**Comment by vighneshmufc** [comment]
Fixed.
