### ISSUE TITLE
Having to Scroll to Reach Feedback Button and Grammar Issue

### ISSUE THREAD

**Issue by vighneshmufc** [CLIxIndia-Dev/clixoer#101]
**Having to Scroll to Reach Feedback Button**
Having to Scroll to Reach Feedback Button , first time users wouldn't understand also correct the grammar in the button
![Screenshot (358)](https://user-images.githubusercontent.com/14256897/102209589-f8ae9500-3ef6-11eb-9a21-06ec08e7181c.png)

**Comment by yogeshu** [comment]
Image is a larger file even if it makes it as per own dimension it will take same size and leave some.  I have given some dimension to the image to adjust it check if this work on 176 
![Screenshot from 2020-12-16 11-51-11](https://user-images.githubusercontent.com/32289745/102312734-424dbd00-3f95-11eb-8f5b-2db29aa741be.png)

**Comment by vighneshmufc** [comment]
176 showing this 
![Screenshot (49)](https://user-images.githubusercontent.com/14256897/102329496-7e414c00-3fae-11eb-967a-4297adf2fb42.png)

**Comment by yogeshu** [comment]
![Screenshot from 2020-12-16 17-40-10](https://user-images.githubusercontent.com/32289745/102347054-ddf72180-3fc5-11eb-9b85-9eb3c7345b14.png)

**Comment by vighneshmufc** [comment]
![Screenshot (50)](https://user-images.githubusercontent.com/14256897/102486391-f7b06b80-408e-11eb-8844-42ad2dee8fc9.png)

Update staging only then i can see this
