### ISSUE TITLE
Correct Grammar on Header on Website

### ISSUE THREAD

**Issue by vighneshmufc** [CLIxIndia-Dev/clixoer#102]
**Correct Grammar on Header on Website**
Correct Grammar on Header on Website.

Please give feedback and help us improve. Take quick survey.
Change to 
Please give us feedback and help us improve. Take our quick survey.

**Comment by yogeshu** [comment]
![Screenshot from 2020-12-16 11-54-57](https://user-images.githubusercontent.com/32289745/102312900-9193ed80-3f95-11eb-97d4-2fad0a074421.png)

**Comment by vighneshmufc** [comment]
looks good

**Comment by vighneshmufc** [comment]
needs to be in staging before closing

**Comment by vighneshmufc** [comment]
Fixed.
