### ISSUE TITLE
Missing i2c Module in Modules section

### ISSUE THREAD

**Issue by vighneshmufc** [CLIxIndia-Dev/clixoer#113]
**Describe the bug**
In Order to Increase reliability 
As a Test Engineer
I Want to see all13 Modules when i click on Modules Button instead of 12

**Test Case**
Given Oer Landing page
When clicked on modules
Then show all 13 instead of 12 modules

**To Reproduce**
1. Go to 'https://clixoer.tiss.edu/5752ad5a2e01310a05dca583/e-library'
2. Click on 'modules'
3. Scroll down to 'pagination'

**Expected behavior**
I2C module is missing

**Screenshots**
![Screenshot (399)](https://user-images.githubusercontent.com/14256897/115177301-8d671080-a0ec-11eb-9391-c15ffa7adac7.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [chrome]
 - Version [e.g. 89]

**Comment by DurgaSwetha** [comment]
Fixed this issue

**Comment by DurgaSwetha** [comment]
I am not able to reproduce this..

**Comment by VirajUtekar** [comment]
This issue is been resolved, on staging environment i2c module is available 

**Screenshot**
![Screenshot from 2021-09-22 11-08-45](https://user-images.githubusercontent.com/90617515/134288973-b1776e7e-27f1-48f6-a379-aa5451bbd14e.png)
