### ISSUE TITLE
Spelling mistake in Tiss-Cool page

### ISSUE THREAD

**Issue by VirajUtekar** [CLIxIndia-Dev/clixoer#140]
**Describe the bug**
 1. There is an Spelling mistake for content as "Dat\a" under Ground Assessment research heading in Tiss-Cool page
 2. Spelling mistake for facebook social connect link (i.e."ceteri.tiss") under cool newsletter in Tiss-Cool page

**To Reproduce**
1. Go to '' "
2. Scroll down to ground assessment research heading and cool newsletter heading
3. See error 

**Expected behavior**
  should contain correct spelling

**Screenshots**
![Screenshot from 2021-09-21 10-32-03](https://user-images.githubusercontent.com/90617515/134119239-41b2f46b-89fa-445e-b089-2dfa7c9bc0d4.png)

![Screenshot from 2021-09-24 11-33-17](https://user-images.githubusercontent.com/90617515/134626054-ad159f07-2303-4d36-b2b4-37fa702299e6.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu 18.04.5 LTS]
 - Browser [Chrome]
 - Version [93]

**Comment by DurgaSwetha** [comment]
Fixed

**Comment by VirajUtekar** [comment]
This issue is been resolved
![Screenshot from 2021-10-11 10-43-55](https://user-images.githubusercontent.com/90617515/136736709-d767ae6b-edb6-4959-94dd-c88e40c6ea8a.png)
