### ISSUE TITLE
The site connect link in footer of Tiss-Cool and Cool-Oer page , alignment is not proper for small screen device resolution

### ISSUE THREAD

**Issue by VirajUtekar** [CLIxIndia-Dev/clixoer#145]
**Describe the bug**
  The alignment of link in footer(i.e. site links ) in Tiss-Cool and Cool-Oer page  is not proper for following small screen device resolution
motoG4
GalaxyS5
Pixel 2
Pixel 2XL
Iphone 5/SE
Iphone 6/7/8
Iphone 6/7/8 plus
Iphone X

**To Reproduce**
1. Go to 'https://staging-clixoer.tiss.edu/home/e-library'
2. Click on 'Tiss-Cool or Cool-Oer' main navigation link
3. Scroll down to 'footer' site connect link

**Expected behavior**
the alignment of site connect link in footer should be proper for responsive screen

**Screenshots**
![Screenshot from 2021-09-21 13-29-51](https://user-images.githubusercontent.com/90617515/134135519-6f313d33-9255-49dd-b003-92a84db2b870.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu 18.04.5 LTS]
 - Browser [Chrome]
 - Version [93]

**Comment by DurgaSwetha** [comment]
Not a issue as such.
