### ISSUE TITLE
There is available of Language Support "marathi" with no resource available in COOL-OER page

### ISSUE THREAD

**Issue by VirajUtekar** [CLIxIndia-Dev/clixoer#149]
**Describe the bug**
  In Language support filter option for resources, (i.e."marathi") has no resource available in cool-oer page

**To Reproduce**
1. Go to 'https://staging-clixoer.tiss.edu/cool/oer'
2. select 'Marathi' as option under Language support filter category
3. See error

**Expected behavior**
  If there is no resource available for any language, the language category should not be displayed

**Screenshots**
 
![Screenshot from 2021-09-22 16-17-31](https://user-images.githubusercontent.com/90617515/134330738-26c40c43-982c-48ce-ae39-f8fa8d8f1d34.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu 18.04.5 LTS]
 - Browser [Chrome]
 - Version [93]

**Comment by DurgaSwetha** [comment]
It has been discussed with the team and no action needed.
