### ISSUE TITLE
Share Button on OER Resources

### ISSUE THREAD

**Issue by vighneshmufc** [CLIxIndia-Dev/clixoer#22]
### Share Button on OER Resources Issue
Share button on OER Resources does not redirect to actual resource page for any of the options . It is copying link to home page always . 
![Screenshot (284)](https://user-images.githubusercontent.com/14256897/89036915-356c5c00-d35b-11ea-8d81-9f02b0d9470f.png)

**Comment by yogeshu** [comment]
#2 about this. The function uses the copy url methods to show or share details of the page, The Card we have in the page lack of their own address or id so it is not possible so share card itself that is why there is page url

**Comment by yogeshu** [comment]
@vighneshmufc Please check

**Comment by vighneshmufc** [comment]
https://staging-clixoer.tiss.edu/cool/oer/5ecd3bc8f731ad332c295749

This is the link for geogebra.. Ideally the share option should have this link rather than home page of website 

@SadaqatMulla  Please confirm 

None of the share button works as intended as far as my opinion is concerned

**Comment by yogeshu** [comment]
**update**
1. each module share contains url of cool preview page 
     - copy link ex- https://clixoer.tiss.edu/cool/oer/5f200bb4f731ad27ef62c187
     - face book 
     - twitter 
     - Telegram

**Comment by yogeshu** [comment]
R&D - 
To get the url of Preview page In COOL oer page and That have to get store in copy link button took a lot of efforts and different function as we use a loop to get cards the value store in the copy on click is same for all cards and that is error 
- To do Item (the process of finding a solution  okay ) 
- Get the Link to the preview page ( same which we are sharing ) and store it in card copy link 
- Get the same link in Facebook share, twitter, telegram, etc
- The logic is different for each share 
- The click function works on the first click and store the same value that is an error we want a different value 
  so decided to try some logic in js to get a unique copy link ( href which is copied is not string url but custom url base of logic ) 
The logic works as per the given condition and try and error method/use that logic in the loop and works fine 
-- the task is done 

 

-This is done as I added a copy link button to fetch the URL of the preview page on the base of logic

**Comment by vighneshmufc** [comment]
Cannot Access Page on Sandbox.. Server Error

**Comment by yogeshu** [comment]
it is done as per url changes in the cool oer page . check all option and copy button @vighneshmufc

**Comment by vighneshmufc** [comment]
Waiting on Staging update

**Comment by vighneshmufc** [comment]
Closed.
