### ISSUE TITLE
FONT AWESOME UPDATION 

### ISSUE THREAD

**Issue by yogeshu** [CLIxIndia-Dev/clixoer#30]
**Is your feature request related to a problem? Please describe.**
NEW VERSION OF FONT AWESOME IS ON WAY AND SOME ICON IS NOT SUPPORTED BY THE THE VERSION[ VERSION HERE ]  WE HAVE TO TAKE NEW VERSION 

**Describe the solution you'd like**
WE ADDED NEW ICON IN COOL PAGE AND NAVBAR BUT THEY ARE INVISIBLE AS THEY COME IN NEW VERISON OF FONT AWESOME ( I HAD DISCUSSION WITH FONT AWESOME DEV TEAM AND THEY SUGGESTED TO USE NEW VERSION ) THAT WILL SUPPORT FOR ALL ICONS 
**Describe alternatives you've considered**
USING IMAGE INSTEAD OF ICON'S ( SOME ISSUE INTHIS TYPE ) 
**Additional context**
WILL ADD IN FUTURE

**Comment by yogeshu** [comment]
The suggestion not to change the file but use icons which support the file we are using ( font awesome  ) check icon of Tiss cool and COOL-OER 
This updated,
@vighneshmufc

**Comment by yogeshu** [comment]
This updated and commit number is c15dec25fae7757fc0c1df962e2623407961fa08 please check and close @vighneshmufc

**Comment by vighneshmufc** [comment]
Closed.
