### ISSUE TITLE
Add team members in the COOL Team slider Cards on COOL Page 

### ISSUE THREAD

**Issue by yogeshu** [CLIxIndia-Dev/clixoer#32]
Coming Soon
 Team member names are missing in Slider Card in Cool 
 

 NO names are provided. - dependency 
 The slider is in the replacement process so It is good so can do both 
 COOL page

**Comment by SadaqatMulla** [comment]
@yogeshu  Add card wise names in the order given below:

- [ ] I.  **Resources for Teacher Education**

1. Ananaya Chatterji
2. Anusha Ramanathan
3. Cecilia D'Costa
4. Daniel D'Souza
5. Emaya Kannamma
6. Farrah Kerawalla
7. Gomathi Jatin
8. Jyoti Bhatia
9. Kinkini Dutta
10. Madhuja Golatkar
11. Mythili Ramchand
12. Piyush Prakash
13. Rajni Kumari
14. Ruchi Kumar

- [ ] II. **Ground Assessment - Research report and Podcast**

1. Ajay Singh
2. Anu Joy
3. Dhipthi Dhona
4. Geetha M
5. Jennifer Thomas
6. Kamakshi 
7. Lalbiakdiki Hnamte
8. Manshvi Palan
9. Nishevita Jayendran
10. Padma Sarangapani
11. Rajasekhar
12. Ramaa Muthukumaran
13. Rekha Pappu
14. Saurav Mohanty
15. Shashank Parimi
16. Soham Bhattacharya
17. Surbhi Nagpal

- [ ] III. **Multilingual Webinars for school teachers and students by ITE & CLIx**

1. Amitabh Anand
2. Bindu Thirumalai
3. Rafikh Shaikh
4. Roshan Singh
5. Sohini Sen
6. Sumegh Paltiwale
7. Tushar Goel
8. Uchita Bakshani
9. Ishmeet Kaur

- [ ] IV. **Technologies for Online Learning in School Education**
1. Amina Charania
2. Omkar Balli 
3. Roshan Singh
4. Sadaqat Mulla
5. Sohini Sen
6. Sumegh Paltiwale

- [ ] V. **COOL-OER Repository**
1. Amitabh Anand
2. Arushi Bansal
3. Brij Kishore
4. Devandhiran Duraipandi
5. Diksha Rehal
6. Emaya Kannamma
7. Nikita Dhokale
8. Raju Sambari
9. Ramesh Nagula
10. Sadaqat Mulla
11. Saurabh Thakur

- [ ] VI. **Communications**
1. Anusha Ramanathan
2. Deepa Bhalerao
3. Garima Singh
4. Jennifer Thomas
5. Manshvi Palan
6. Omkar Balli 
7. Satej Shende
8. Sayan Bhattacharya
9. Shiva Thorat
10. Surbhi Nagpal

- [ ] VII. **Production & Technology**
1. Durga Garapati
2. Ramesh Khade
3. Sadaqat Mulla
4. Satej Shende
5. Sayan Bhattacharya
6. Shiva Thorat
7. Shivani Dixit
8. Vighnesh Nair
9. Yogesh Bhavsar

- [ ] VIII. **Project Management**
1. Deepa Bhalerao
2. Garima Singh
3. Manshvi Palan
4. Omkar Balli 
5. Padma Sarangapani
6. Poonam Sachdev
7. Pratima Zore
8. Vishal Kshirsagar

**Comment by yogeshu** [comment]
Done
