### ISSUE TITLE
update TISS-COOL page details 

### ISSUE THREAD

**Issue by yogeshu** [CLIxIndia-Dev/clixoer#33]
Coming Soon
#update tiss page details like given on tiss.edu

**Comment by yogeshu** [comment]
#update the cool page as per document or Tiss.edu cool page

**Comment by yogeshu** [comment]
#will update details as per document and this website page

**Comment by SadaqatMulla** [comment]
Tasks/issues should be crisp and clear.

 Aug 20, 2020
**Task Description:** 
Content on TISS-COOL page (https://clixoer.tiss.edu/cool) should be updated with latest additions. 
Reference: https://tiss.edu/view/6/mumbai-campus/centre-for-education-innovation-and-action-researc/activities-of-centre-2/connected-open-online-learning-cool/

**Comment by SadaqatMulla** [comment]
Review of TISS-COOL page:

**Task Description:**
1. With conent update initiative panels are becoming long scroll. Please add "Read more >" to expand additional text and "Read less [down arrow]" to un-expand.

2. In section "2. Ground Assessment - Research" interchange a and b sub-sections to make panel size smaller.

3. In section "3. Multilingual Webinars.." at the end add a line "Watch webinar recordings on YouTube" (add YT icon and hyperlink below playlist)

https://www.youtube.com/playlist?list=PL8bZzoltbMJkIo5zvqo2t5SCbF01npcwh

4. Update section-4 text COOL-OER
`4. Content Curation: OER Repository`
"A repository of open educational resources (OER) has been developed where high quality OER have been curated with meta-tagging of subjects, grades, language support, type of technology etc. The COOL-OER will help teachers, parents, students and educators to search high quality resources which are free and open as well as curated with guidance for use and integration. The resources have been selected which foster active learning , are multilingual (support Indian languages), accessible and adaptable. The COOL-OER repository can be accessed at https://clixoer.tiss.edu/cool/oer 
Please visit the webpage for more details. You can also share more OERs with us. 
On the website you can also access award winning multilingual CLIx resources pertaining to Digital literacy, English, Mathematics and Science for middle and high school students."

5. Add "COOL NEWSLETTERS" in ToC and align the text size with sections.

**Comment by SadaqatMulla** [comment]
Review of TISS-COOL page:

Sept 01, 2020
1. In section "1.Resources for Teacher Education" at the bottom after a line separator add
a) `Access resources on www.tissx.tiss.edu ` (make link clickable) 
b)  `Watch TALC and DSERT webinar recordings on YouTube" (add YT icon and hyperlink below playlist)
https://www.youtube.com/watch?v=DBAh7HqJkYI&list=PL8bZzoltbMJn_vm2yKN7gZINB6aVbfsQ5

2. Let `Read more` buttons remain at its position and just change the direction of arrow.
 "Read more >" to expand additional text and "Read less [down arrow]" to un-expand.

3. In section " 2. Ground Assessment.." place `Read more` button just before posdcast listing table in sub-section **b**

**Comment by yogeshu** [comment]
The changes are done please review

**Comment by SadaqatMulla** [comment]
@yogeshu it seems content update of `section 4` and point #3 in the sept 01 review still remains (176 instance)?

**Comment by yogeshu** [comment]
I had changed the content as per suggestion some tags were unclosed. please verify now and comment if any change

**Comment by SadaqatMulla** [comment]
Now most of changes are looking in place.

In Section 5, towards the end of paragraph, some textual changes are needed:

> So far more than 1300 teachers have enrolled in this course. We have recently announced digital badges. Learners who complete the course will receive the ‘Course Completer’ digital badge.

**Comment by yogeshu** [comment]
done

**Comment by SadaqatMulla** [comment]
@yogeshu Looks good. work with @shivani2314 to update staging alongwith `task #52` Update #3 COOL-OER 
@vighneshmufc please take care of testing.

**Comment by shivani2314** [comment]
Staging has been updated. @vighneshmufc please go ahead with the testing.

**Comment by vighneshmufc** [comment]
![Screenshot (310)](https://user-images.githubusercontent.com/14256897/92711764-70a87480-f376-11ea-903e-144c1c519b6e.png)
@yogeshu  the names and the issue 2 has wrong PDF .. Correct the same

**Comment by vighneshmufc** [comment]
![Screenshot (311)](https://user-images.githubusercontent.com/14256897/92712026-bbc28780-f376-11ea-85a2-608315a9e288.png)
The Know more at number 4 opening on the same page itself.. Add target Blank

**Comment by vighneshmufc** [comment]
![Screenshot (312)](https://user-images.githubusercontent.com/14256897/92712154-ea406280-f376-11ea-8984-07d27b4a3e29.png)
Instagram link redirects to twitter

**Comment by yogeshu** [comment]
This is updated please review and close the task

**Comment by vighneshmufc** [comment]
Closed.
