### ISSUE TITLE
Add Counter's on the cool oer cards - ( numbers) 

### ISSUE THREAD

**Issue by yogeshu** [CLIxIndia-Dev/clixoer#34]
Coming Soon
#add counter to cool page

**Comment by yogeshu** [comment]
the counter has been added to the OER card For **Preview** And **Explore Link**, please verify

**Comment by yogeshu** [comment]
@vighneshmufc  @SadaqatMulla

**Comment by vighneshmufc** [comment]
Please Describe the issue properly.. Not sure what this means

**Comment by DurgaSwetha** [comment]
> Please Describe the issue properly.. Not sure what this means

This is mainly showing the number of visits to preview, explore link being shown next to the icon on the COOL OER card..

**Comment by yogeshu** [comment]
This is updated @vighneshmufc

**Comment by yogeshu** [comment]
This is updated . the commit is f52e77ceca8b233a30c922da449093a181713b2d please check and verify @vighneshmufc

**Comment by vighneshmufc** [comment]
Closed.
