### ISSUE TITLE
adding images for resource type on card as per tags ( resource ) 

### ISSUE THREAD

**Issue by yogeshu** [CLIxIndia-Dev/clixoer#35]
**Image as per Resource Type **

1. The COOL OER page have Cards as per Resources Each Card show Resource Type 
2. The Image around the Tag is similar for All Resources That is not ideal 
3. Change The Images to identify Card as per different resource Type 
Update :

**Comment by yogeshu** [comment]
It is done in 176 will be push for testing of change

**Comment by vighneshmufc** [comment]
Can u explain properly with images ..this isnt clear

**Comment by yogeshu** [comment]
![Screenshot from 2020-11-04 10-10-37](https://user-images.githubusercontent.com/32289745/98069910-04ce1e00-1e86-11eb-9864-71609484008d.png)
Images on Card  Resource Type - Tool etc

**Comment by yogeshu** [comment]
![Screenshot from 2020-11-04 10-10-37](https://user-images.githubusercontent.com/32289745/98069961-2cbd8180-1e86-11eb-914e-7518d9f12056.png)
The Images In Resouce Type - like Tool
Now Resouce Type has a different image as per the type

**Comment by VirajUtekar** [comment]
This issue is been solved as all the favicon icons for resource type category matches with favicon for resources present on to list
