### ISSUE TITLE
The alignment of text in cool page - details of cool oer 

### ISSUE THREAD

**Issue by yogeshu** [CLIxIndia-Dev/clixoer#37]
**- Text To update**

1. Change All Paragraph's First Letter To Capital 
2. Remove If any misplaced Text in The page

**Comment by yogeshu** [comment]
This is updated @vighneshmufc

**Comment by yogeshu** [comment]
This is closed the commit is f52e77ceca8b233a30c922da449093a181713b2d please check and close @vighneshmufc

**Comment by vighneshmufc** [comment]
Please update details in task..cannot understand anything..

**Comment by yogeshu** [comment]
1. The Task was to make paragraph change with capital word and some text change @vighneshmufc

**Comment by vighneshmufc** [comment]
Please add links of original document in Description

**Comment by yogeshu** [comment]
Done
