### ISSUE TITLE
Improper File Name of Unplatform Download

### ISSUE THREAD

**Issue by vighneshmufc** [CLIxIndia-Dev/clixoer#43]
**Improper File Name of Unplatform Download**
Improper File Name of Unplatform Download . Please Remove the extra .exe

**To Reproduce**
1. Go to 'https://clixoer.tiss.edu/home/e-library'
2. Click on 'Unplatform Download'
3. See error

**Expected behavior**
Name to Be Proper

**Screenshots**
![Screenshot (294)](https://user-images.githubusercontent.com/14256897/91258828-e9aaa800-e78a-11ea-9b21-e5db9f2ef3ef.png)

**Comment by DurgaSwetha** [comment]
@yogeshu Please chk this.

**Comment by yogeshu** [comment]
This is updated @vighneshmufc #

**Comment by yogeshu** [comment]
This updated . commit is 4f8c7482eaefc03648f0763000eefd637d374678 please check and verify @vighneshmufc
