### ISSUE TITLE
Unplatform Does not download Completely and Stops at 1 GB

### ISSUE THREAD

**Issue by vighneshmufc** [CLIxIndia-Dev/clixoer#44]
**Unplatform Download**
Unplatform Does not download Completely and Stops at 1 GB.

**To Reproduce**
1. Go to 'https://clixoer.tiss.edu/home/e-library'
2. Click on 'Unplatform Download'
3. See error

**Expected behavior**
Should Download Fully

**Screenshots**
![Screenshot (295)](https://user-images.githubusercontent.com/14256897/91259119-7c4b4700-e78b-11ea-817e-ebd601641e2b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 84

**Comment by DurgaSwetha** [comment]
Have tested this multiple times and it happens to be replicating only on windows 10..As i am able to properly download on windows 7.@shivani and @vighneshmufc are also in loop.

**Comment by vighneshmufc** [comment]
@SadaqatMulla Please review

**Comment by shivani2314** [comment]
Cannot recreate the issue. Tried on the same configurations as mentioned by @vighneshmufc

**Comment by vighneshmufc** [comment]
Still buggy for me so kept it open
