### ISSUE TITLE
Names of Module overlapping badge

### ISSUE THREAD

**Issue by vighneshmufc** [CLIxIndia-Dev/clixoer#45]
**Names of Module overlapping badge**
Names of Module overlapping badge on 1920*1080

**To Reproduce**
1. Go to 'https://staging-clixoer.tiss.edu/home/e-library/'
2. Scroll down to 'Geometric Reasoning Part 1'
3. See error

**Expected behavior**
Full Name should be visible properly.

**Screenshots**
![Screenshot (296)](https://user-images.githubusercontent.com/14256897/91291795-32765700-e7b3-11ea-994a-52a937c9891e.png)

**Comment by yogeshu** [comment]
It's done. please check and update the status

**Comment by vighneshmufc** [comment]
Yes can see the changes . Thank you . Please Create PR for the same

**Comment by yogeshu** [comment]
This is updated @vighneshmufc
