### ISSUE TITLE
Align Icon and Text Properly in TOC

### ISSUE THREAD

**Issue by vighneshmufc** [CLIxIndia-Dev/clixoer#46]
**Align Icon and Text Properly in TOC**
Align Icon and Text Properly in TOC with proper space. Follow one convention. For Example English Icon and Maths Icon has no Space and then Text however Science has a space. Similarly There is space is Modules and Handbook

**To Reproduce**
1. Go to 'https://staging-clixoer.tiss.edu/home/e-library/'
2. Scroll down to 'TOC'
3. See error

**Expected behavior**
Alignment Should be Proper

**Screenshots**
![Screenshot (298)](https://user-images.githubusercontent.com/14256897/91292264-e37cf180-e7b3-11ea-9748-29a3af0d086c.png)

**Comment by yogeshu** [comment]
![Screenshot from 2020-08-31 11-25-28](https://user-images.githubusercontent.com/32289745/91687140-b26a3b80-eb7c-11ea-8f55-49de57e7167f.png)
Please Check if it is okay

**Comment by vighneshmufc** [comment]
No it isnt ...i can still see spaces between icon and Text .. For eg. Science

**Comment by yogeshu** [comment]
updated. varify and let me know if there are any more change

**Comment by vighneshmufc** [comment]
Please add SS

**Comment by yogeshu** [comment]
![Screenshot from 2020-09-07 16-05-57](https://user-images.githubusercontent.com/32289745/92378862-1912ca80-f124-11ea-9e41-94c26c50fbc9.png)
please check

**Comment by yogeshu** [comment]
![Screenshot from 2020-09-07 16-07-12](https://user-images.githubusercontent.com/32289745/92378934-33e53f00-f124-11ea-8863-512b3abee0c8.png)

**Comment by vighneshmufc** [comment]
Fix it for Modules, Interactives and Handbooks too

**Comment by yogeshu** [comment]
I check it Not possible for those as its image with own width and height which gives them padding around a text - ex 
![Screenshot from 2020-09-08 10-37-37](https://user-images.githubusercontent.com/32289745/92435208-6001ce00-f1bf-11ea-9d6a-aa8d969cf715.png)

**Comment by vighneshmufc** [comment]
@SadaqatMulla  Please Review ...Apparently the space cannot be removed after the Icon and before Text in Interactives Modules and Handbooks 

@yogeshu Its done properly for subjects why cant you use that style ?

**Comment by yogeshu** [comment]
I clearly said that it is an image element and the one I settle is icons so we have a difference here. 
I can fix this with some avoidable practices in CSS need to look for it as a priority.

**Comment by yogeshu** [comment]
![Screenshot from 2020-09-21 10-54-54](https://user-images.githubusercontent.com/32289745/93734997-08208980-fbf9-11ea-99eb-f4b31db5bcb6.png)
@vighneshmufc  check

**Comment by vighneshmufc** [comment]
Looks Better now... Topic Closed
