### ISSUE TITLE
Next prev button should disable if no next/previous element exist

### ISSUE THREAD

**Issue by vighneshmufc** [CLIxIndia-Dev/clixoer#51]
**Next prev button should disable if no next/previous element exist**
As you scroll around modules we see a pagination which has Next and Prev button always enable which confuses the user.
**To Reproduce**
1. Go to 'https://clixoer.tiss.edu/home/e-library'
2. Scroll down to 'Pagination'
3. See error

**Expected behavior**
The Next and Previous Button should disable based on conditions met . 

**Screenshots**
![Screenshot (306)](https://user-images.githubusercontent.com/14256897/92349479-d89b5880-f0f3-11ea-8a2a-e5b3966381ef.png)

**Comment by yogeshu** [comment]
It is done in 176 setup will update it in next updation of testing change

**Comment by yogeshu** [comment]
It's done check! on 176 for update @vighneshmufc

**Comment by vighneshmufc** [comment]
Testing only gonna be done on staging to avoid confusions

**Comment by vighneshmufc** [comment]
@yogeshu Use a different color to show disabled buttons

**Comment by yogeshu** [comment]
@vighneshmufc  that worked on default class of bootstrap and I have written some script to add disabled to the previous script will check if I can do that and update it.

**Comment by vighneshmufc** [comment]
Closed.
