### ISSUE TITLE
Interactive Card Content Button to Play Online/Offline not visible with long descriptions

### ISSUE THREAD

**Issue by vighneshmufc** [CLIxIndia-Dev/clixoer#59]
**Describe the bug**
In Interactives - Interactive Card Content Button to Play Online/Offline not visible with long descriptions

**To Reproduce**
1. Go to 'https://clixoer.tiss.edu/5752ad5a2e01310a05dca583/e-library' in Telegu
2. Click on 'Interactives'
3. Scroll down to 'Any Long Interactives'

**Expected behavior**
The Buttons should be aligned properly

**Screenshots**
![Screenshot (317)](https://user-images.githubusercontent.com/14256897/93070202-2ee03c80-f69c-11ea-9431-3b87d1a48ca1.png)

**Comment by yogeshu** [comment]
This issue is not found 
![Screenshot from 2020-09-14 16-53-58](https://user-images.githubusercontent.com/32289745/93080184-e67c4b00-f6aa-11ea-9a67-73bd0fbaa756.png)

**Comment by vighneshmufc** [comment]
Not Fixed

**Comment by yogeshu** [comment]
This issue is in the windows machine will take this up and try to fix it

**Comment by VirajUtekar** [comment]
this issue is been resolved, on production site as all the interactive cards on flip has two action button(i.e. explore online, download offline) when selected telugu as language
