### ISSUE TITLE
The COOL Page Filter View  ( responsive ) 

### ISSUE THREAD

**Issue by yogeshu** [CLIxIndia-Dev/clixoer#65]
**The Responsive Filter In Tiss COOL PAGE**

-The  COOL OER page has a filter menu based on subject etc, that so the issue is when you scroll on the same page we have a sticky sidebar that helps the user to navigate but if we use the filter under it that sticky sidebar has to remove and function like normal sidebar so the user can check all filter

- The Mobile View of the filter has to be a button ( toggle ) that hide and show the sidebar - like add the reference here 

**Describe alternatives you've considered**
 For now none  

**Additional Context**
 WE have to check if we can have different sidebar or remove sticky opinion is good

**Comment by yogeshu** [comment]
The First Version for The mobile Responsive view is updated 
check 
![Screenshot from 2020-09-30 16-40-45](https://user-images.githubusercontent.com/32289745/94678241-cc459c80-033b-11eb-9478-cefae15f9080.png)
![Screenshot from 2020-09-30 16-40-09](https://user-images.githubusercontent.com/32289745/94678244-ce0f6000-033b-11eb-87ed-dba7deae000b.png)

**Comment by yogeshu** [comment]
The Toggle Sidebar Filter is Button that opens the menu and you can change the filter in it. 
- Update can add close button but it depends on the filter function - okay

**Comment by yogeshu** [comment]
The Fix for some responsiveness added
The button is missing as it's required to  change all of the code which is mismatching the filter rendering so it can be taken up later

**Comment by vighneshmufc** [comment]
#81 issue added
