### ISSUE TITLE
Responsiveness Testing of COOL OER , TISS COOL , cool preview page 

### ISSUE THREAD

**Issue by yogeshu** [CLIxIndia-Dev/clixoer#66]
**Responsiveness Testing of COOL OER , TISS COOL , cool preview page **
- Test on Desktop with 1024px
- Test on Tablet 
- Test on Mobile 
- Deep testing with version of browsers
 etc

**Comment by vighneshmufc** [comment]
Have added Issues #77 #78 #76 in response
