### ISSUE TITLE
Pink Shade in Mobile View of Filter

### ISSUE THREAD

**Issue by vighneshmufc** [CLIxIndia-Dev/clixoer#81]
**Describe the bug**
There is a Pink Shade in Mobile View of Filter

**To Reproduce**
Open Filter option on Mobile 
**Expected behavior**
Clean Design

**Screenshots**
![photo6129574001555647442](https://user-images.githubusercontent.com/14256897/98083543-86cb4080-1ea0-11eb-8a41-1829117025a4.jpg)

**Comment by yogeshu** [comment]
Okay will change the color

**Comment by vighneshmufc** [comment]
Fixed. Thank you
