### ISSUE TITLE
Images Missing in Content and Filter Option

### ISSUE THREAD

**Issue by vighneshmufc** [CLIxIndia-Dev/clixoer#83]
**Describe the bug**
Icon Images Missing in Content and Filter Option

**Screenshots**
![Screenshot (342)](https://user-images.githubusercontent.com/14256897/98107048-f56bc680-1ebf-11eb-9247-7d63349053b9.png)
![Screenshot (343)](https://user-images.githubusercontent.com/14256897/98107062-f8ff4d80-1ebf-11eb-84d6-84a9984948a9.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vighneshmufc** [comment]
@yogeshu

**Comment by yogeshu** [comment]
I got the Idea

**Comment by vighneshmufc** [comment]
Fixed.
