### ISSUE TITLE
PHET Tamil Tool Text Out of View

### ISSUE THREAD

**Issue by vighneshmufc** [CLIxIndia-Dev/clixoer#85]
**Describe the bug**
PHET Tamil Tool Text Out of View

**Screenshots**
![Screenshot (346)](https://user-images.githubusercontent.com/14256897/98107575-b722d700-1ec0-11eb-8bc8-c853c1972240.png)

**Comment by yogeshu** [comment]
![Screenshot from 2020-11-05 09-09-41](https://user-images.githubusercontent.com/32289745/98194966-a87f0300-1f46-11eb-9a24-919c4f81cadb.png)

**Comment by yogeshu** [comment]
I havent found the issue but will increase size to make sure it stay in line.

**Comment by vighneshmufc** [comment]
@yogeshu Please link commit here

**Comment by yogeshu** [comment]
#82 commmit for this include code for this issue

**Comment by vighneshmufc** [comment]
Clsoed.
