### ISSUE TITLE
Filter Option Needs Tool Tip Explaining Types as Explained in SRS Slide

### ISSUE THREAD

**Issue by vighneshmufc** [CLIxIndia-Dev/clixoer#86]
**Is your feature request related to a problem? Please describe.**
Filter Option Needs Tool Tip Explaining Types as Explained in SRS Slide [Here](https://docs.google.com/presentation/d/1ivAPOnd9aXzfNQCtjQuRFx2Iw9nk7PWfM7mNTe9D7XU/edit#slide=id.g74b266a43a_0_22)
**Describe the solution you'd like**
Add Too Tips explaining what filters are

**Comment by DurgaSwetha** [comment]
Filter functionality is a feature request. All the 18 cool oers which are displayed on COOL-Oer tab should get filtered upon selection and the count for the same has to be reflected along side..

**Comment by DurgaSwetha** [comment]
These multiple filters are similar to any other site...where any number of filter option selection will apply and condition and thus the oers matching the criteria will be shown

**Comment by DurgaSwetha** [comment]
Reg the tool tip @yogeshu can confirm is he has received the same

**Comment by vighneshmufc** [comment]
Yes But the SRS said there needs to be a Tool Tip for the same ..hence raised this

**Comment by yogeshu** [comment]
I have already created an issue for tooltips and I haven't received any tooltips so in the last meeting agree on taking this later when  tootlips will be provided for all cool pages . @vighneshmufc @DurgaSwetha

**Comment by vighneshmufc** [comment]
@SadaqatMulla Please review

**Comment by SadaqatMulla** [comment]
Yes it is there in SRS but as discussed in last meeting the filters seem self explanatory. We can consider tool tips in the next release (if needed). 
However, if you see any tool tips are substantially affecting user experience we can work on such specific scenarios right away.

**Comment by vighneshmufc** [comment]
Clsoed.
