### ISSUE TITLE
Clicking on Tamil Language Filter Looks buggy 

### ISSUE THREAD

**Issue by vighneshmufc** [CLIxIndia-Dev/clixoer#88]
**Describe the bug**
Clicking on Tamil Language Filter Looks buggy as it takes times to load so the filter looks like its reloading itself

**To Reproduce**
1. Go to 'Language Support of Filter'
2. Click on 'Tamil'

**Screenshots**
![Screenshot (351)](https://user-images.githubusercontent.com/14256897/98108844-a4a99d00-1ec2-11eb-88ec-d053936c7854.png)

**Comment by vighneshmufc** [comment]
Update not just Tamil Randomly few Filters takes time loading

**Comment by DurgaSwetha** [comment]
Mention the combinations for which it takes time to load...

**Comment by DurgaSwetha** [comment]
I have tried with Tamil multiple other filter but couldnt replicate the said scenario..

**Comment by vighneshmufc** [comment]
Its random for me.. Happening while you change filters repeatedly
check that way maybe

**Comment by DurgaSwetha** [comment]
The count seems buggy working on it...

**Comment by DurgaSwetha** [comment]
> The count seems buggy working on it...

This issue has been rectified and pushed on to repo.. @vighneshmufc let me know if this can be taken onto staging

**Comment by vighneshmufc** [comment]
Yes please go ahead

**Comment by vighneshmufc** [comment]
Closed.
