### ISSUE TITLE
Include "TISS-COOL" and "COOL-OER" page visit counts in CLIxOER website stats

### ISSUE THREAD

**Issue by SadaqatMulla** [CLIxIndia-Dev/clixoer#91]
Include "TISS-COOL" and "COOL-OER" page visit counts in [CLIxOER website stats](https://docs.google.com/spreadsheets/d/1y6WgwJ-0IOhQmBfbdXDRp_DYU365KF18rCPiKHiaMLU/edit?usp=sharing) 
URLs:
1. clixoer.tiss.edu/cool
2. clixoer.tiss.edu/cool/oer

Note: The visitor may or may NOT click anything within the page like ToC, oer card etc. This count should be independent of those within-page clicks.

**Comment by DurgaSwetha** [comment]
Changes pushed on to 176 post testing

**Comment by vighneshmufc** [comment]
Fixed.
