### ISSUE TITLE
Update COOL-OER page content with Google form link etc.

### ISSUE THREAD

**Issue by SadaqatMulla** [CLIxIndia-Dev/clixoer#93]
- [ ] Under "About COOL-OER" section place "Read more" button after line ending with "guided by a six point rubric:"

- [ ] Before "Contact Us" section add below line in font size ~30px 

![Brain-bulb](https://user-images.githubusercontent.com/26817843/101161120-186fce80-3656-11eb-82c3-2c9ddecb1dee.png) Do you know of any interesting OER? Curate and submit [here](https://forms.gle/z8cL3Xv1ewv3vQHW9).

Note: 
1. Form link https://forms.gle/z8cL3Xv1ewv3vQHW9
2. svg file of icon can is on [COOL-OER-icons](https://drive.google.com/drive/u/1/folders/16bfgMMaY9inCi8qKcKRdyqzaktdBsSdr) clixindia drive folder.

**Comment by vighneshmufc** [comment]
Works. Closed

**Comment by SadaqatMulla** [comment]
@vighneshmufc I dont see this on staging screen shot taken at 19:23hrs. Am I missing anything? @yogeshu 

![Screenshot from 2020-12-07 19-22-38](https://user-images.githubusercontent.com/26817843/101359025-b0bdbb80-38c1-11eb-84d6-cbc938ab392d.png)

**Comment by vighneshmufc** [comment]
Change the placement of the text

**Comment by vighneshmufc** [comment]
Works
