### ISSUE TITLE
Fetch CLIxOER stats between Dec 6, 2019 to Dec 6, 2020

### ISSUE THREAD

**Issue by SadaqatMulla** [CLIxIndia-Dev/clixoer#95]
- [x] Fetch CLIxOER stats between Dec 6, 2019 to Dec 6, 2020
CLIxOER stats - https://docs.google.com/spreadsheets/d/1y6WgwJ-0IOhQmBfbdXDRp_DYU365KF18rCPiKHiaMLU/edit?usp=sharing 
- [x] Create graph of monthly trend in hits/visitors
- [ ] Identify top 10 most popular/accessed resources
- [x] Create any other useful graphs

**Comment by shivani2314** [comment]
Stats updated along with all the required graphs. 
Doc containing the stats: https://docs.google.com/spreadsheets/d/1y6WgwJ-0IOhQmBfbdXDRp_DYU365KF18rCPiKHiaMLU/edit#gid=1828319395.

**Comment by SadaqatMulla** [comment]
> Stats updated along with all the required graphs.
> Doc containing the stats: https://docs.google.com/spreadsheets/d/1y6WgwJ-0IOhQmBfbdXDRp_DYU365KF18rCPiKHiaMLU/edit#gid=1828319395.

Thanks much @shivani2314 

@DurgaSwetha can you tell which all hits/views might not have been captured here?
I dont see any entries for About + Help pages + (TISS-COOL + COOL-OER).
