### ISSUE TITLE
Website overlay to share feedback survey and showcase popular resources on clixoer website

### ISSUE THREAD

**Issue by SadaqatMulla** [CLIxIndia-Dev/clixoer#97]
Website overlay to share feedback survey and showcase popular resources on clixoer website. There are two sub-tasks:

- [ ] for survey there can be a top bar that user can close without take survey as well. The bar can remain across website sections unless closed by users. 
The bar can be plain black with white text or glossy-black
Reference https://storyweaver.org.in/

Text: Please give feedback and help us improve. Take quick survey.
Hyperlink `quick survey` to open below google form in a new tab.
Survey form link: https://forms.gle/32RNzpNnVbvzDPXa6 

- [ ] showcasing popular resources can be through an overlay such as https://cpd.tiss.edu/rtict/ 
- Need to appear only on landing page
- see if it can display resources as viewed on website or 
- can have a graphic image + a button to goto that resource
- can a YouTube video be added?
- user should also be able to close the overlay with mouse + keyboard

References:
- 

Both should be such they can be enabled and disabled easily.

**Comment by vighneshmufc** [comment]
for survey there can be a top bar that user can close without take survey as well. The bar can remain across website sections unless closed by users.
@yogeshu The bar is visible only on Home Page
